import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:kottra_app/models/attendance_record.dart';
import 'package:kottra_app/models/late_excuse_request.dart';
import 'package:kottra_app/services/attendance_service.dart';
import 'package:kottra_app/services/late_excuse_service.dart';

class LateExcuseViewModel extends ChangeNotifier {
  LateExcuseViewModel({
    required this.storeId,
    required this.employeeId,
    required this.employeeName,
    LateExcuseService? lateExcuseService,
    AttendanceService? attendanceService,
  })  : _lateExcuseService = lateExcuseService ?? LateExcuseService(),
        _attendanceService = attendanceService ?? AttendanceService() {
    _subscribe();
  }

  final String storeId;
  final String employeeId;
  final String employeeName;

  final LateExcuseService _lateExcuseService;
  final AttendanceService _attendanceService;

  StreamSubscription<List<LateExcuseRequest>>? _requestSub;
  StreamSubscription<List<AttendanceRecord>>? _attendanceSub;

  List<LateExcuseRequest> _requests = [];
  List<AttendanceRecord> _history = [];
  bool _isLoading = false;
  bool _disposed = false;

  List<LateExcuseRequest> get requests => _requests;
  bool get isLoading => _isLoading;

  /// Late days the employee can still request an excuse for: actually late,
  /// not already forgiven, and without an existing pending or approved request.
  List<AttendanceRecord> get excusableLateDays {
    final blockedDates = _requests
        .where((r) => r.status != LateExcuseStatus.rejected)
        .map((r) => _dayKey(r.date))
        .toSet();

    return _history
        .where((a) =>
            a.lateMinutes > 0 &&
            !a.lateExcused &&
            !blockedDates.contains(_dayKey(a.date.toDate())))
        .toList();
  }

  String _dayKey(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

  void _subscribe() {
    if (employeeId.isEmpty) return;

    _requestSub?.cancel();
    _requestSub = _lateExcuseService
        .streamEmployeeRequests(storeId, employeeId)
        .listen((data) {
      _requests = data;
      if (!_disposed) notifyListeners();
    });

    _attendanceSub?.cancel();
    _attendanceSub = _attendanceService
        .streamHistory(storeId, employeeId, limit: 60)
        .listen((data) {
      _history = data;
      if (!_disposed) notifyListeners();
    });
  }

  Future<void> submitRequest({
    required AttendanceRecord record,
    required String reason,
  }) async {
    if (employeeId.isEmpty) {
      throw Exception('Employee ID is missing');
    }
    if (reason.trim().isEmpty) {
      throw Exception('Please provide a reason.');
    }

    _isLoading = true;
    notifyListeners();

    try {
      final request = LateExcuseRequest(
        id: '', // Generated by Firestore.
        storeId: storeId,
        employeeId: employeeId,
        employeeName: employeeName,
        date: record.date.toDate(),
        attendanceId: record.id,
        lateMinutes: record.lateMinutes,
        reason: reason.trim(),
        status: LateExcuseStatus.pending,
      );
      await _lateExcuseService.submitRequest(request);
    } finally {
      _isLoading = false;
      if (!_disposed) notifyListeners();
    }
  }

  @override
  void dispose() {
    _disposed = true;
    _requestSub?.cancel();
    _attendanceSub?.cancel();
    super.dispose();
  }
}
