import 'dart:async';
import 'dart:io';


import 'package:flutter/foundation.dart';
import 'package:kottra_app/models/leave_request.dart';
import 'package:kottra_app/services/leave_service.dart';
import 'package:file_picker/file_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';

class LeaveViewModel extends ChangeNotifier {
  LeaveViewModel({
    required this.storeId,
    required this.employeeId,
    required this.employeeName,
  }) {
    _subscribeToLeaves();
  }

  final String storeId;
  final String employeeId;
  final String employeeName;
  final LeaveService _leaveService = LeaveService.instance;

  StreamSubscription<List<LeaveRequest>>? _leaveSub;
  List<LeaveRequest> _leaves = [];
  bool _isLoading = false;

  List<LeaveRequest> get leaves => _leaves;
  bool get isLoading => _isLoading;

  void _subscribeToLeaves() {
    if (employeeId.isEmpty) return;
    _leaveSub?.cancel();
    _leaveSub = _leaveService.streamEmployeeLeaves(storeId, employeeId).listen((data) {
      _leaves = data;
      notifyListeners();
    });
  }

  Future<void> submitRequest({
    required DateTime startDate,
    required DateTime endDate,
    required LeaveType type,
    required String reason,
    String? actionedBy,
    PlatformFile? attachment,
  }) async {
    if (employeeId.isEmpty) {
      throw Exception('Employee ID is missing');
    }
    
    if (startDate.isAfter(endDate)) {
      throw Exception('Start date must be before or equal to end date.');
    }
    if (reason.trim().isEmpty) {
      throw Exception('Please provide a reason.');
    }

    _isLoading = true;
    notifyListeners();

    try {
      String? attachmentUrl;
      if (attachment != null) {
        final storageRef = FirebaseStorage.instance
            .ref()
            .child('hr_leave_requests/$employeeId/${DateTime.now().millisecondsSinceEpoch}_${attachment.name}');
            
        if (kIsWeb && attachment.bytes != null) {
          final uploadTask = await storageRef.putData(attachment.bytes!);
          attachmentUrl = await uploadTask.ref.getDownloadURL();
        } else if (attachment.path != null) {
          final file = File(attachment.path!);
          final uploadTask = await storageRef.putFile(file);
          attachmentUrl = await uploadTask.ref.getDownloadURL();
        }
      }

      final request = LeaveRequest(
        id: '', // Will be generated by Firestore
        storeId: storeId,
        employeeId: employeeId,
        employeeName: employeeName,
        startDate: startDate,
        endDate: endDate,
        type: type,
        status: LeaveStatus.pending,
        reason: reason,
        actionedBy: actionedBy,
        attachmentUrl: attachmentUrl,
      );

      await _leaveService.submitLeaveRequest(request);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  @override
  void dispose() {
    _leaveSub?.cancel();
    super.dispose();
  }
}
