import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:kottra_app/models/hr_employee.dart';
import 'package:kottra_app/models/salary_advance.dart';
import 'package:kottra_app/services/salary_advance_service.dart';

class SalaryAdvanceViewModel extends ChangeNotifier {
  SalaryAdvanceViewModel({
    required this.storeId,
    required this.employeeId,
    required this.employeeName,
    required this.currency,
    SalaryAdvanceService? advanceService,
  }) : _advanceService = advanceService ?? SalaryAdvanceService() {
    _subscribeToAdvances();
  }

  final String storeId;
  final String employeeId;
  final String employeeName;

  /// The employee's salary currency; advances are requested in this currency.
  final SalaryCurrency currency;

  final SalaryAdvanceService _advanceService;

  StreamSubscription<List<SalaryAdvance>>? _advanceSub;
  List<SalaryAdvance> _advances = [];
  bool _isLoading = false;
  bool _disposed = false;

  List<SalaryAdvance> get advances => _advances;
  bool get isLoading => _isLoading;

  /// Outstanding = approved advances not yet deducted, in the employee's
  /// currency. This is the amount the next payroll run will deduct.
  double get outstandingBalance {
    final total = _advances
        .where((a) => a.status == AdvanceStatus.approved)
        .fold<double>(0, (sum, a) => sum + a.amount);
    return (total * 100).roundToDouble() / 100;
  }

  void _subscribeToAdvances() {
    if (employeeId.isEmpty) return;
    _advanceSub?.cancel();
    _advanceSub =
        _advanceService.streamEmployeeAdvances(storeId, employeeId).listen((data) {
      _advances = data;
      if (!_disposed) notifyListeners();
    });
  }

  Future<void> submitAdvance({
    required double amount,
    required String reason,
  }) async {
    if (employeeId.isEmpty) {
      throw Exception('Employee ID is missing');
    }
    if (amount <= 0) {
      throw Exception('Please enter a valid amount.');
    }

    _isLoading = true;
    notifyListeners();

    try {
      final advance = SalaryAdvance(
        id: '', // Generated by Firestore.
        storeId: storeId,
        employeeId: employeeId,
        employeeName: employeeName,
        amount: amount,
        currency: currency,
        reason: reason.trim(),
        status: AdvanceStatus.pending,
      );
      await _advanceService.submitAdvanceRequest(advance);
    } finally {
      _isLoading = false;
      if (!_disposed) notifyListeners();
    }
  }

  @override
  void dispose() {
    _disposed = true;
    _advanceSub?.cancel();
    super.dispose();
  }
}
